#!/usr/bin/env ruby

require 'pathname'
require 'shellwords'

case ARGV[0]
when "home", nil, ""
  remote_mount_point = "/home/tom"
when "root"
  remote_mount_point = "/"
else
  remote_mount_point = ARGV[0]
end

exec "sshfs tom@owlbear:#{remote_mount_point} #{Shellwords.shellescape ((Pathname.new(Dir.home) + "sshfs") + "owlbear").cleanpath.to_s}"
