#!/bin/bash

command_exists () {
  type "$1" &> /dev/null ;
}

if command_exists java ; then
  run_dir=`pwd`
  robostring_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/RoboString
  cd $robostring_dir
  java RoboString $1
  cd $run_dir
else
  echo "java not found"
fi

