#!/usr/bin/env ruby

case ARGV[0]
when "production", "prod", "p"
  subdomain = "production"
when "staging", "stag", "s"
  subdomain = "staging"
else
  subdomain = ARGV[0]
end

exec "ssh -i ~/.ssh/aws-lsi-streaming/TwinEngine root@#{subdomain}.livingscriptures.com"