#!/usr/bin/env ruby

case ARGV[0]
when "stream", "production", "prod", "p"
  subdomain = "stream"
when           "staging",    "stag", "s"
  subdomain = "staging"
else
  raise "Invalid subdomain"
end

exec "ssh -i ~/.ssh/aws-lsi-streaming/TwinEngine root@#{subdomain}.livingscriptures.com"