#!/usr/bin/env ruby

case ARGV[0]
when "prod", "p"
  subdomain = "production"
when "stag", "s"
  subdomain = "staging"
when "sw"
  subdomain = "staging-web01"
when "pw"
  subdomain = "production-web01"
else
  subdomain = ARGV[0]
end

exec "ssh -i ~/.ssh/aws-lsi-streaming/TwinEngine root@#{subdomain}.livingscriptures.com"