#!/usr/bin/env ruby

require 'shellwords'
require 'resolv'
require 'socket'
require 'fileutils'
require 'pathname'

user = "tom"
host = "owlbear"
smut_path = Pathname.new("/home/tom/.porn/Unsorted").cleanpath

begin
  Resolv.getaddress host
rescue Resolv::ResolvError
  puts "Unable to resolve hostname \"#{host}\"; aborting"
  abort
end

if Socket.ip_address_list.map(&:ip_address).include? Resolv.getaddress(host)
  puts "scp does not work for transferring files " <<
    "between locations on the same system; aborting."
  abort
end

user = "tom"
host = "owlbear"
smut_path = Pathname.new("/home/tom/.porn/Unsorted")

begin
  Resolv.getaddress host
rescue Resolv::ResolvError
  puts "Unable to resolve hostname \"#{host}\"; aborting"
  abort
end

files_to_copy = []

ARGV.each do |fn|

  unless File.exist? fn
    puts "File \"#{fn}\" does not exist; skipping"
    next
  else
  files_to_copy << fn
  end

end

`scp #{files_to_copy.map{ |fn| Shellwords.shellescape fn }.join(" ")} #{user}@#{host}:#{Shellwords.shellescape(smut_path)}`

if $?.exitstatus == 0
  puts "scp exit status 0; removing local files"
  files_to_copy.each do |fn|
    puts "Transferred #{fn} with exit-status 0. Removing file."
    FileUtils.rm fn
  end
end