#!/usr/bin/env ruby

default_device_file = "~/creds_luks"

device_file = ARGV[0] || default_device_file
mapper_file_basename = "creds"
mapper_file = "/dev/mapper/" << mapper_file_basename

unless File.exists? mapper_file
  %x{sudo cryptsetup open #{device_file} #{mapper_file_basename}}
end

if File.exists? mapper_file
  %x{sudo mount #{mapper_file} /home/tom/creds}
else
  abort
end