#!/usr/bin/env ruby

mapper_file_basename = "creds"
mapper_file = "/dev/mapper/" << mapper_file_basename

%x{sudo umount /home/tom/creds}

if File.exists? mapper_file
  %x{sudo cryptsetup close #{mapper_file_basename}}
end
