#!/usr/bin/env ruby

$brightness_file_path = "/sys/class/backlight/intel_backlight/brightness"

max_brightness = 5273
current_brightness = File.read($brightness_file_path).to_i

percentages_valid = 0..100
words_valid = [:up, :down, :max, :mid, :min, :low, :off]


def write_to_file(value)
  value = value.to_i if value.respond_to? :to_i
  exec %Q{echo #{value} | } +
       %Q{sudo tee "#{$brightness_file_path}"}
end


multiplier = nil
word = nil


if words_valid.include? ARGV[0].to_sym
  word = ARGV[0].to_sym
elsif (ARGV[0] =~ /\d+/) && (percentages_valid.include?(ARGV[0].to_i))
  multiplier = ARGV[0].to_i / 100.0
else
  puts "Argument must be an integer between #{percentages_valid},\n" +
    "or one of the following words: #{words_valid}"
  exit(1)
end


if multiplier
  write_to_file (multiplier * max_brightness).to_i
elsif word
  increment = max_brightness * 0.2
  case word
  when :up
    desired_brightness = current_brightness + increment
  when :down
    desired_brightness = current_brightness - increment
  when :max
    desired_brightness = max_brightness
  when :mid
    desired_brightness = max_brightness / 2.0
  when :low
    desired_brightness = max_brightness * 0.1
  when :min, :off
    desired_brightness = 0
  end
  write_to_file desired_brightness
end

exit(0)
